### ISSUE TITLE
Timesheet entry is not taking in a right direction

### ISSUE THREAD

**Issue by kaashyap123** [saineshwar/WebTimeSheetManagement#2]
Hi when I select a date, list of projects getting displayed. When I enter the data for the same day across all projects and saving it is getting saved. Let us say when I enter data for May 21 across all projects and saving it is not getting saved. When I choose the same date it is saying already filled.

Also how can I show the data in read only mode, instead of displaying alert. When displaying all timesheet when there is no data for few columns it is displaying the description

![issue](https://user-images.githubusercontent.com/39486775/40316358-b86cc0f6-5d3b-11e8-9e99-b9211bc16809.PNG)

**Comment by saineshwar** [comment]
Can you show send a document with snapshot while filling a timesheet which will help to resolve this issue?
