### ISSUE TITLE
WebTimeSheetManagement (load failed)

### ISSUE THREAD

**Issue by TriLogic** [saineshwar/WebTimeSheetManagement#5]
Downloaded, unzippped and attempted to load the solution with Visual Studio 2017 and received the following error:

Creation of the virtual directory http://localhost:49649/ failed with the error:

Filename: //?F:\Learning\mvc\WebTimeSheetManagement-master\.vs\Config\applicationhost.config

Error: Cannot read configuration file

**Comment by saineshwar** [comment]
Just deleted a folder named .vs which is there in the folder and then try to run.

![2018-12-31 22_27_22-webtimesheetmanagement-master](https://user-images.githubusercontent.com/8281689/50564501-5158e780-0d4b-11e9-946a-1a90e8e99dc9.png)
